# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1120, 760)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.img_out = QtWidgets.QGraphicsView(self.centralwidget)
        self.img_out.setObjectName("img_out")
        self.horizontalLayout.addWidget(self.img_out)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mode1 = QtWidgets.QRadioButton(self.centralwidget)
        self.mode1.setChecked(True)
        self.mode1.setObjectName("mode1")
        self.horizontalLayout_2.addWidget(self.mode1)
        self.mode2 = QtWidgets.QRadioButton(self.centralwidget)
        self.mode2.setObjectName("mode2")
        self.horizontalLayout_2.addWidget(self.mode2)
        self.mode3 = QtWidgets.QRadioButton(self.centralwidget)
        self.mode3.setObjectName("mode3")
        self.horizontalLayout_2.addWidget(self.mode3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.result = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.result.setFont(font)
        self.result.setObjectName("result")
        self.verticalLayout.addWidget(self.result)
        self.answer = QtWidgets.QTextBrowser(self.centralwidget)
        self.answer.setObjectName("answer")
        self.verticalLayout.addWidget(self.answer)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 7)
        self.verticalLayout.setStretch(2, 10)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "御坂学习强国助手"))
        self.mode1.setText(_translate("MainWindow", "挑战答题"))
        self.mode2.setText(_translate("MainWindow", "争上游答题"))
        self.mode3.setText(_translate("MainWindow", "双人对战"))
        self.answer.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p></body></html>"))
